# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2017

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
#platform:
#  - x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON

# only build PR but not branch as well
skip_branch_with_pr: true

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
#  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

# clone directory
clone_folder: C:\dronecode_sdk


# scripts to run before build
before_build:

  - cd C:\dronecode_sdk
  - git submodule update --init --recursive --depth 100
  - cd C:\

build: on

build_script:
  - set CL=/MP
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set dronecode_sdk_dir=C:\dronecode_sdk
  - cd %dronecode_sdk_dir%
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE="%configuration%" -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX=%dronecode_sdk_dir%\install ..
  - cmake --build . --target install --config %configuration%
  - cd %dronecode_sdk_dir%
  - cd example\takeoff_land
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
  - cmake --build . --config %configuration%
  - cd %dronecode_sdk_dir%
  - cd example\fly_mission
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
  - cmake --build . --config %configuration%
  - cd %dronecode_sdk_dir%
  - cd example\offboard_velocity
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
  - cmake --build . --config %configuration%
  - cd %dronecode_sdk_dir%
  - cd example\transition_vtol_fixed_wing
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
  - cmake --build . --config %configuration%
  - cd %dronecode_sdk_dir%
  - cd example\follow_me
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
  - cmake --build . --config %configuration%
  - cd %dronecode_sdk_dir%
  - cd example\fly_qgc_mission
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
  - cmake --build . --config %configuration%
  - cd %dronecode_sdk_dir%

test: on

# We need to manually copy the dlls for now, otherwise they are not found.
test_script:
  - cd %dronecode_sdk_dir%
    #- copy build\src\third_party\gtest\googlemock\gtest\%configuration%\gtestd.lib build\%configuration%\
    #- copy build\src\third_party\gtest\googlemock\gtest\%configuration%\gtest_maind.lib build\%configuration%\
    #- copy build\src\third_party\gtest\googlemock\%configuration%\gmockd.lib build\%configuration%\
    #- copy build\src\plugins\mission\%configuration%\dronecode_sdk_mission.dll build\%configuration%\
    #- copy build\src\plugins\camera\%configuration%\dronecode_sdk_camera.dll build\%configuration%\
    #- copy build\src\plugins\calibration\%configuration%\dronecode_sdk_calibration.dll build\%configuration%\
  - %dronecode_sdk_dir%\build\src\%configuration%\unit_tests_runner.exe
