# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2017

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64

environment:
  CFLAGS: "-D_WIN32_WINNT=0x0600"
  CXXFLAGS: "-D_WIN32_WINNT=0x0600"
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
      - COMPILER: mingw-64
        GENERATOR: MinGW Makefiles
#      - COMPILER: msvc2017
#        GENERATOR: Visual Studio 15 2017
#        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

# only build PR but not branch as well
skip_branch_with_pr: true

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

# clone directory
clone_folder: C:\dronecode_sdk

# scripts to run before build
before_build:
  - if "%COMPILER%"=="mingw-64" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%COMPILER%"=="mingw-64" set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - cd C:\dronecode_sdk
  - git submodule update --init --recursive --depth 100
  - cd C:\

build: on

build_script:
  - set CL=/MP
  - if "%COMPILER%"=="msvc2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set dronecode_sdk_dir=C:\dronecode_sdk
  - cd %dronecode_sdk_dir%
    #- md build
    #- cd build
    #- cmake -DCMAKE_BUILD_TYPE="%configuration%" -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX=%dronecode_sdk_dir%\install -DBUILD_BACKEND=ON ..
  - cmake -DCMAKE_BUILD_TYPE="%configuration%" -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%dronecode_sdk_dir%\install -DBUILD_BACKEND=ON -Bbuild -H.
  - cmake --build build --target install --config %configuration%
    #- cd %dronecode_sdk_dir%
    #- cd example\takeoff_land
    #- md build
    #- cd build
    #- cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
    #- cmake --build . --config %configuration%
    #- cd %dronecode_sdk_dir%
    #- cd example\fly_mission
    #- md build
    #- cd build
    #- cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
    #- cmake --build . --config %configuration%
    #- cd %dronecode_sdk_dir%
    #- cd example\offboard_velocity
    #- md build
    #- cd build
    #- cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
    #- cmake --build . --config %configuration%
    #- cd %dronecode_sdk_dir%
    #- cd example\transition_vtol_fixed_wing
    #- md build
    #- cd build
    #- cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
    #- cmake --build . --config %configuration%
    #- cd %dronecode_sdk_dir%
    #- cd example\follow_me
    #- md build
    #- cd build
    #- cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
    #- cmake --build . --config %configuration%
    #- cd %dronecode_sdk_dir%
    #- cd example\fly_qgc_mission
    #- md build
    #- cd build
    #- cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH="%dronecode_sdk_dir%\install;%dronecode_sdk_dir%\third_party\build\install" ..
    #- cmake --build . --config %configuration%
    #- cd %dronecode_sdk_dir%

test: on

test_script:
  - cd %dronecode_sdk_dir%
  - build\src\unit_tests_runner.exe
  - build\src\backend\test\unit_tests_backend.exe
